name: Test continue-on-error
on:
  workflow_dispatch:
  
  
jobs:
  fail-with-continue-on-error:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      outcome: ${{ steps.recover-output.outputs.outcome }}
    steps:
      - id: failing-step
        run: |
          #exit 1
          echo "Keep on running"
      - id: recover-output
        if: always()
        run: |
          PREVIOUS_STEP_OUTCOME=${{ steps.failing-step.outcome }}
          echo "::set-output name=outcome::"$PREVIOUS_STEP_OUTCOME
        
      
  continue-after-fail:
    needs: fail-with-continue-on-error
    runs-on: ubuntu-latest
    if: needs.fail-with-continue-on-error.outputs.outcome == 'success'
    steps:
      - run: |
          echo job-outcome: ${{ needs.fail-with-continue-on-error.outcome }}
          echo job-result:  ${{ needs.fail-with-continue-on-error.result }}
          echo job-conclusion: ${{ needs.fail-with-continue-on-error.conclusion }}
          echo job2-outcome: ${{ needs.fail-with-continue-on-error.outputs.outcome }}
          echo step-outcome: ${{ needs.fail-with-continue-on-error.steps.failing-step.outcome }}
          echo step-result:  ${{ needs.fail-with-continue-on-error.steps.failing-step.result }}
          echo step-conclusion: ${{ needs.fail-with-continue-on-error.steps.failing-step.conclusion }}
